spring.application.name=kanban

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format_sql=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# ===============================
# ERROR HANDLING
# ===============================
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ===============================
# CORS
# ===============================
cors.allowed-origins=${FRONTEND_URLS}

# ===============================
# SERVER
# ===============================
server.tomcat.max-threads=20
